### ISSUE TITLE
nicehash suppoert information missing

### ISSUE THREAD

**Issue by LeadManPL** [ryo-currency/ryo-pools-json#8]
https://pools.ryoblocks.com/ page does not include information (or i'm blind) which pools support *nicehash* protocol or  nicehash.com support (I'm not sure which sentence is more correct)
Is it possible to include that information, or is *nicehash* related to miners only, not to pools?

**Comment by mosu-forge** [comment]
@LeadManPL nicehash support does need to be enabled at the pool by allowing a high diff port. I don't have this information available in the pools json list, although it is possible I could. However due to our new algo change in the next version it does not make sense to add it unless NH starts offering support for the new algo.
